### ISSUE TITLE
Update scraper to reflect new PPPL structure in Dataspace

### ISSUE THREAD

**Issue by kmcelwee** [pulibrary/dspace-osti#31]
Collection handles presumably remain the same, but we've made assumptions about what collections remain empty. Double check that we have full coverage in `scraper.py`

**Comment by kelynch** [comment]
Adding the following collections:

* Computational Science / PPPL Collaborations (88435/dsp01h702q945b)
* Engineering / Engineering Research (88435/dsp01cf95jf54t)
* ES&H / Technical Reports (88435/dsp017p88ck628)
* IT / PPPL Collaborations (88435/dsp013x816q68n)
* ITER and Tokamaks / PPPL Collaborations (88435/dsp01wm117s06f)
* Theory / Theory (88435/dsp01rn301446q)
