### ISSUE TITLE
Cannot run Poster.py

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-osti#33]
Dry run of the Poster script yields following:

```bash
$ python Poster.py --dry-run
Traceback (most recent call last):
  File "Poster.py", line 9, in <module>
    from ostiapi import ostiapi
ImportError: cannot import name 'ostiapi' from 'ostiapi' (unknown location)
```

**Comment by kmcelwee** [comment]
@kelynch This requires cloning all the content for the submodule. I'll either remove the submodule and add it to `requirements.txt` or I'll update the documentation
