### ISSUE TITLE
User prompt before running test or production post to OSTI

### ISSUE THREAD

**Issue by kelynch** [pulibrary/dspace-osti#53]
When Poster.py successfully runs in test or production mode, it posts a submission to an OSTI ELinks server and emails a number of people, including people at PPPL and OSTI.  Nothing is posted externally and no one is contacted when the script runs in dry-run mode.  This behavior is all indicated in this repo's README but not elsewhere.

Proposal: When running Poster.py, give the user a prompt (ie "Are you sure?  Running in test mode will do the following...") when they run the script in a mode that will send out data submissions and emails.  Consider also indicating that these actions will *not* take place, when the user runs the script in dry-run mode.

**Comment by astrochun** [comment]
Very much like this idea. I can create a PR. This is a fairly straightforward of no more than a few lines of code.
