### ISSUE TITLE
Inconsistent isreferencedby data

### ISSUE THREAD

**Issue by astrochun** [pulibrary/dspace-osti#64]
Recently the smoke test failed: https://github.com/pulibrary/dspace-osti/actions/runs/2596194313

Upon investigation, the problem stems from incorrect `isreferencedby` in the DataCite schema. We have one instance from this failure:
1. 133782, "Initial Results from Boron Powder Injection Experiments in WEST Lower Single Null L-mode Plasmas" (`ark:88435/dsp01cr56n4150`)

Note that the code retrieves the DOIs by stripping off anything prior to `doi.org` (e.g., https://doi.org and https://dx.doi.org). It does not handle the actual redirected URL or `doi:*`

**Comment by astrochun** [comment]
@matthewjchandler or @neggink, can one of you two fix this issue? This is the same as #63 but a different record.

**Comment by matthewjchandler** [comment]
The relation to the paper was given as a direct URL: https://iopscience.iop.org/article/10.1088/1741-4326/ac70ea. I updated it to the DOI: https://doi.org/10.1088/1741-4326/ac70ea.

@astrochun please confirm that the item passes your smoke test now.
